version: '3.8'

services:
  db:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${POSTGRES_DATABASE_NAME}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
        - user_api_nw

  user_api:
    build: .
    container_name: "user-api"
    environment:
      POSTGRES_DATABASE_NAME: "auth"
      POSTGRES_USER: "auth-user"
      POSTGRES_PASSWORD_SECURE: "/db:password"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "db"
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy
      vault:
        condition: service_started
    networks:
      - user_api_nw

  vault:
    image: vault:1.15.0
    ports:
      - "8300:8300"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
      VAULT_DEV_ROOT_TOKEN_ID:  "myroot"


volumes:
  postgres_volume:

networks:
  user_api_nw:
    driver: bridge